% 2/7/18 Chance imported libraries and make them global so that the
% function can access them. myFirstText is the texture generated by the
% function and imagesec is used to display the image. DO NOT change
% imagese!!!

addpath ./ORIGINALS/


load mpLibrary_os;
global mpLibrary s o nVari;
patterns = [];

stimArray = stimGen( 1 , 0);

quiltA = quiltGen(stimArray, 1);

%fprintf('%d', length(quiltA));

% quiltA{1}

for i=1:10
    scrollsubplot(200,200,i); imagesc(quiltA{i}); colormap('gray'); axis square off; 
end

%{
stim.carrPattA = stimArray{1};
stim.carrPattB = stimArray{2};
stim.modType   = 'quilt';
stim.modDepth  = 50; 
stim.carrA.con = 0.14; 
stim.carrB.con = 0.14;


stimImage = stimQuilter(stim);


figure(1)
subplot(1,3,1);
imagesc(stimImage); axis square off; colormap('gray');

subplot(1,3,2);
imagesc(stim.carrPattA); axis square off; colormap('gray');

subplot(1,3,3);
imagesc(stim.carrPattB); axis square off; colormap('gray');
%}



